language: go
sudo: required
go:
- 1.8
- 1.10
- 1.12
- 1.13
install:
  - go get github.com/satori/go.uuid
  - go get github.com/gorilla/websocket
script:
  - go test
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7330c10c-6b17-4902-9f64-0c8ad7e0f259
