language: go
go:
- 1.8
- 1.10
- 1.12
- 1.13

install:
  - go get github.com/satori/go.uuid
  - go get github.com/gorilla/websocket
script:
  - go test
  - go build
after_success:
　- go test -race -coverprofile=coverage.txt -covermode=atomic
　- bash <(curl -s https://codecov.io/bash)
